### ISSUE TITLE
Hangs Neovim

### ISSUE THREAD

**Issue by anuvyklack** [gbprod/yanky.nvim#37]
https://user-images.githubusercontent.com/13056013/180661306-62ba9cd3-b2cc-4a4e-a446-4e86ff26dda1.mp4

I'm able to reproduce this even with minconfig:
```lua
-- nvim --clean -u mini.lua mini.lua
vim.o.packpath = '~/.local/share/nvim/site'

vim.cmd 'packadd yanky'
require('yanky').setup({})
```

I'm using `nvim 7.2` and Fedora 36 with Wayland.

**Comment by anuvyklack** [comment]
It seems, the problem is in Wayland: if I add in my config 
```lua
  system_clipboard = {
    sync_with_ring = false,
  },
```
This behavior does not appear.

**Comment by gbprod** [comment]
Hello @anuvyklack !
Thanks for reporting this issue.
Looks like the same issue than #20 and #21.

Seems to be caused by a `xclip` random bug :/

In this case, you can try 

1. Update `xclip` to the last version

2. Use `xsel` instead of `xclip` with this code:

```lua
vim.g.clipboard = {
  name = "xsel_override",
  copy = {
    ["+"] = "xsel --input --clipboard",
    ["*"] = "xsel --input --primary",
  },
  paste = {
    ["+"] = "xsel --output --clipboard",
    ["*"] = "xsel --output --primary",
  },
  cache_enabled = 1,
}
```
3. You can also try to use the [debug-freeze](https://github.com/gbprod/yanky.nvim/tree/debug-freeze) branch instead of `main` and let me know if if fix the problem :sweat_smile:

**Comment by anuvyklack** [comment]
No, [debug-freeze](https://github.com/gbprod/yanky.nvim/tree/debug-freeze) branch doesn't help.

**Comment by gbprod** [comment]
I've you tried xsel ?
What's your version of xclip ?

**Comment by anuvyklack** [comment]
I am using Fedora, so I have the latest `xclip` 0.13.

**Comment by anuvyklack** [comment]
xsel is working. wl-clipbord --- not, the same behaviour as for xlip.

**Comment by anuvyklack** [comment]
Highlight doesn't work. Can open a separate issue. And default history length 100, but in README written that 10.

**Comment by ray-x** [comment]
I see the same issue.
one work around is use `<C-c>` to back to normal mode.

**Comment by gbprod** [comment]
@anuvyklack 

> `xsel` is work. But when I copy something outside the Nvim and paste with `p`, I can't choose it direct with `<C-p>` --- get `Reached first item` message. But if I paste with `p`, and then press `<C-n><C-p>` I get the clipboard content.

I think #43 will fix this issue.

> Highlight doesn't work. 

I think #40 fix this issue, can you confirm ?

@ray-x 

> I see the same issue on archlinux. one workaround is to use `<C-c>` to back to normal mode.

I've you tried using `xsel` ?

**Comment by ray-x** [comment]
I did not config `xsel`  in my setup.

**Comment by bezmi** [comment]
Using `xsel` as you've described on gnome 42 (wayland) fixes these clipboard issues for me.

**Comment by lalitmeeq** [comment]
I am using nightly neovim and I am also facing this issue. I was not sure what was causing the issue. Then tried pressing `<C-c>` while the neovim is hanged and it came out of the process. Then I checked `Lazy profile` and it showed the issue that `yanky.nvim` is taking a lot of time for doing something behind the scenes.

**Comment by folke** [comment]
Should be fixed in my PR. Would be great if anyone else could confirm.

**Comment by azmodude** [comment]
> Should be fixed in my PR. Would be great if anyone else could confirm.

@folke I am on https://github.com/gbprod/yanky.nvim/commit/32882f6d3e7bbc8687a71540a695853036511b2c, but unfortunately still see the infinite focus gained/lost loop on Gnome46/Fedora40. Disabling yanky fixes it.

**Comment by folke** [comment]
@azmodude what clipboard tool is used? wl-clipboard? or something else?

**Comment by folke** [comment]
Probably because the clipboard tool only closes (and returns focus to Neovim) a while after getting the clipboard contents.
I'll see if there's something else that can be done to prevent this.

**Comment by folke** [comment]
@azmodude I've created a new PR that might fix the issue you're still having.

Would be great if you could test to see if it works https://github.com/gbprod/yanky.nvim/pull/184

**Comment by azmodude** [comment]
@folke You are a legend. :1st_place_medal: This fixes the infinite loop.
I am still seeing a tiny empty space popping up and vanishing in dash-to-dock when switching focus, but no more lockups.
